KablamoOSS/kombustion

- docs/README.md
Nice to have the documentation on the docs pages.
> Add code counter to documentation

- cloudformation/template.go
Completely passes through the resource for any Custom:: types, avoiding generated parsers.
> Custom resource handling

- internal/tasks/upsert.go
- main.go
This fixes #11.
However, this area still needs good tests.
> added support for all capabilities and a shorthand --iam.

- Gopkg.lock
- config/errors.go
- internal/cloudformation/parameters.go
- internal/cloudformation/parameters_test.go
- internal/cloudformation/tasks/upsert.go
- internal/manifest/init.go
- internal/manifest/manifest.go
- internal/manifest/write.go
- internal/plugins/add.go
- internal/plugins/load.go
- internal/plugins/lock/update.go
- internal/tasks/add.go
- internal/tasks/flags.go
- internal/tasks/generate.go
- internal/tasks/upsert.go
- main.go
- vendor/github.com/KablamoOSS/go-cli-printer/printer.go
Fix for #21 
Values in `.enivronment[env].parameters` will now be used for Parameters in stacks.
>  Change environment.yaml to pull from kombustion.yaml

- .gitignore
- internal/cloudformation/template.go
- internal/cloudformation/template_test.go
Wasn't able to test logFileError function. It's logging with fmt.Print at the moment, and I can't get the stdout for assertion.
If I swap to logrus the format for the line output is lost.
> Template tests “fixes #35”

- Gopkg.lock
- internal/plugins/load.go
- internal/plugins/load_test.go
- internal/plugins/marshalling_test.go
- pkg/plugins/api/api_test.go
- pkg/plugins/api/types/types.go
- vendor/github.com/KablamoOSS/go-cli-printer/printer.go
> ensure restricted prefixes cannot be used

- documentation/content/api/cli.md
- internal/cloudformation/parameters_test.go
- internal/cloudformation/template.go
- internal/cloudformation/template_test.go
- internal/manifest/manifest_test.go
- internal/manifest/types.go
- internal/plugins/add_test.go
- internal/tasks/generate.go
- internal/tasks/upsert.go
> HideDefaultExports changed to GenerateDefaultOutputs

- pkg/plugins/api/api_test.go
- pkg/plugins/api/marshalling.go
> added cleaner to prevent null values from being output

- internal/cloudformation/tasks/upsert.go
- internal/tasks/upsert.go
- internal/tasks/utils.go
> add upsert flag to tag stack

- internal/manifest/types.go
- internal/tasks/upsert.go
> add per-environment tags to kombustion.yaml

- internal/manifest/init.go
- internal/manifest/init_test.go
- internal/manifest/manifest.go
- internal/manifest/write.go
Refactors `surveyForInitialManifest` to facilitate testing and includes a handful of tests, which could be expanded on.
> Manifests tests

- internal/plugins/load.go
- internal/plugins/lock/load.go
- internal/plugins/lock/plugin.go
- internal/plugins/lock/update.go
- internal/plugins/lock/write.go
> Check plugin hash before loading

- internal/tasks/delete.go
> Fixes --environment for delete

- pkg/parsers/intrinsics/intrinsics.go
Adds a creator for most of the intrinsic functions for use in plugins.
> Added intrinsic function creators

- internal/cloudformation/tasks/events.go
> FIX: Print out events

- documentation/content/api/cli.md
- internal/manifest/init.go
- internal/manifest/init_test.go
- internal/manifest/manifest.go
- internal/manifest/write.go
- internal/plugins/add.go
- internal/tasks/add.go
- internal/tasks/delete.go
- internal/tasks/delete_test.go
- internal/tasks/events.go
- internal/tasks/events_test.go
- internal/tasks/flags.go
- internal/tasks/generate.go
- internal/tasks/generate_test.go
- internal/tasks/init.go
- internal/tasks/upsert.go
- internal/tasks/upsert_test.go
Adds support for overriding the filepath of the manifest file.
> Work for overriding the manifest file location

- generate/main.go
> Fix for specification file mismatch #121

- types/types.go
> Added DeletionPolicy

- internal/cloudformation/tags.go
> added Condition as an intrinsic

- internal/cloudformation/template.go
- internal/cloudformation/template_parsers_test.go
- internal/tasks/upsert.go
This fixes a regression introduced into `v0.5.0`
> fix regression that caused outputs to stop generating
